route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'AI-Server'
            channel: '#production_tracking'
            api_url: 'https://hooks.slack.com/services/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'
